### ISSUE TITLE
Question - can I have some information about the plan for backend integration?

### ISSUE THREAD

**Issue by jungpark-mlir** [microsoft/triton-shared#21]
Hi,

I really appreciate that this project has been released, it widens opportunities for both triton itself and ecosystem, thanks.
Especially, I'm looking forward to seeing the full integration with pytorch.
As I'm currently considering the design of the backend compiler and runtime, very curios how triton-shared would be integrated into the e2e pipeline and which options will be available in the example backend.

My question is,
1. I guess not but, are you plan to include GPU backend as well? 
2. When do you expect the example backend could be released? roughly

Regards,
Jungwook

**Comment by manbearian** [comment]
Hi @jungpark-mlir . Thanks for question.

I have plans to release a prototype CPU back-end that uses this work, but i don't have a timeline yet.

There are no plans right now for GPU.

I've talked to a few folks in the industry that are looking at building accelerator (non-GPU) backends using this work as well, but again no timelines.
