### ISSUE TITLE
Send mail to dev team on workflow failure

### ISSUE THREAD

**Issue by manbearian** [microsoft/triton-shared#23]
Looks like we need to customize our Actions to mail the dev team on workflow failure, otherwise only the creator of the workflow (last editor) gets mail on failure.

**Comment by nhat-nguyen** [comment]
I just did a little of searching and looks like GitHub doesn't have any option to customize this behaviour of only notifying the last user who modifies the pipeline. There's some third-party GitHub action that can be used to send email, but that requires having an email account already set up: https://github.com/marketplace/actions/send-email

**Comment by manbearian** [comment]
Something like this might work:
```sh
gh --repo ${{ github.repository }} issue create --title "this is a bug" --body "Nofify @manbearian, this job has failed"
```
