### ISSUE TITLE
Several errors in triton-to-linalg pass

### ISSUE THREAD

**Issue by yuanfz98** [microsoft/triton-shared#7]
Hello,

We are trying to convert from ttirs to linalg in nanoGPT model and have encountered some edge cases that triton-to-linalg pass failed to lower. 

https://drive.google.com/drive/folders/1oBIJFhdL8TQO2PIF_PsUaMJRPVMPJ6G7?usp=sharing

Thank you for your help.

**Comment by manbearian** [comment]
Thank you for the report. it looks like there are a number of unfinished/incomplete items you're running into with this collection of inputs. 

I'm seeing the following unique failures:
```
UNREACHABLE executed at src/triton/third_party/triton_shared/lib/Analysis/PtrAnalysis.cpp:377!
triton-shared-opt: .triton/llvm/llvm+mlir-17.0.0-x86_64-linux-gnu-ubuntu-18.04-release/include/llvm/Support/Casting.h:566: decltype(auto) llvm::cast(const From&) [with To = mlir::MemRefType; From = mlir::Type]: Assertion `isa<To>(Val) && "cast<Ty>() argument of incompatible type!"' failed.
triton-shared-opt: src/triton/third_party/triton_shared/lib/Conversion/TritonToLinalg/TritonToLinalg.cpp:335: virtual mlir::LogicalResult {anonymous}::AssertConverter::matchAndRewrite(mlir::triton::AssertOp, mlir::OpConversionPattern<mlir::triton::AssertOp>::OpAdaptor, mlir::ConversionPatternRewriter&) const: Assertion `condVal && condVal.getType().isa<mlir::IntegerType>() && "Only asserts on scalars are currently supported"' failed.
error: Only support lowering reduction with body containing 1 maxf or addf.
error: Scalar load is currently not supported
error: failed to legalize operation 'tt.load'
error: other value used in masked load produced by unsupported instruction
```

here's a log of all the failures:
[bugs.log](https://github.com/microsoft/triton-shared/files/12785938/bugs.log)

**Comment by makslevental** [comment]
@manbearian if you create a tracking issue (or whatever) for these (and others), I'm sure some of us adoring fans would be glad to pitch in (including appropriate RFC and design discussion and etc. of course). At least I know I would.

**Comment by manbearian** [comment]
> @manbearian if you create a tracking issue (or whatever) for these (and others), I'm sure some of us adoring fans would be glad to pitch in (including appropriate RFC and design discussion and etc. of course). At least I know I would.

done!

From the items i created supporting additional reductions seem the most straightforward if you're looking for a nice on ramp :)

**Comment by nhat-nguyen** [comment]
> Hello,
> 
> We are trying to convert from ttirs to linalg in nanoGPT model and have encountered some edge cases that triton-to-linalg pass failed to lower.
> 
> https://drive.google.com/drive/folders/1oBIJFhdL8TQO2PIF_PsUaMJRPVMPJ6G7?usp=sharing
> 
> Thank you for your help.

@yuanfz98 Thanks for sharing these! Would you mind also sharing us the triton code that produces these IR? It would help us a lot in understanding the usage of certain triton language features.
