### ISSUE TITLE
[Potential Bug]: sanity check mulState handling of modulos

### ISSUE THREAD

**Issue by haishanzzzz** [microsoft/triton-shared#79]
### Additional information

In the `PtrState::mulState` function, we [directly assign](https://github.com/microsoft/triton-shared/blob/3230526f95f7e73f1885b9c9d008b1aec535f2d2/lib/Analysis/PtrAnalysis.cpp#L144C3-L144C26) the only modulos present in the two operands to the result. I am trying to understand if that is the correct behavior.

E.g,. consider the following examples:
```
%0 = tl.arange(0, 4)
%1 = arith.remsi %0, %cst3
%2 = arith.muli %1, %cst4
```

Each of these values should contain:
```
%0: [0, 1, 2, 3]
%1: [0, 1, 2, 0]
%2: [0, 4, 8, 0]
```

Should we also multiply the modulo OFRs accordingly?

**Comment by nhat-nguyen** [comment]
Thanks for noticing this. I agree this doesn't look right. I haven't put much thought into understanding what multiplying a modulo expression would mean (it might not make sense). What do you think about just asserting that we *are not* dealing with modulo in a `mul`?

**Comment by haishanzzzz** [comment]
Thank you for confirming! I believe we can just multiply the modulos field with the corresponding scalar in mulState to address this pattern.

FWIW, I am working on a version of the PtrAnalysis with the goal to separate the Pointer and mask analysis from Memref and Linalg lowering, hence these questions. Will post more details soon. cc @manbearian
